CREATE DATABASE PW_AUTOS;
USE PW_AUTOS;

CREATE TABLE PERSONAL (
	ID_PERSONAL CHAR(10) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(150) NOT NULL,
	TELEFONO CHAR(10) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ID_ROL VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTES ( 
	ID_CLIENTE CHAR(10) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(150) NOT NULL,
	TELEFONO CHAR(10) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL
);

CREATE TABLE MARCAS (
	ID_MARCA CHAR(20) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MODELOS (
	ID_MODELO CHAR(20) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE,
	ID_MARCA CHAR(20) NOT NULL,

	CONSTRAINT FOREIGN KEY(ID_MARCA) REFERENCES MARCAS(ID_MARCA)
);

CREATE TABLE OPCIONES (
	ID_OPCIONES CHAR(10) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(150) NOT NULL,
	PRECIO DOUBLE NOT NULL
);

CREATE TABLE MODELO_OPCIONES (
	ID_MODELO CHAR(20) NOT NULL,
	ID_OPCIONES CHAR(10) NOT NULL,

	PRIMARY KEY(ID_MODELO, ID_OPCIONES),

	CONSTRAINT FOREIGN KEY(ID_OPCIONES) REFERENCES OPCIONES(ID_OPCIONES),
	CONSTRAINT FOREIGN KEY(ID_MODELO) REFERENCES MODELOS(ID_MODELO)
);

CREATE TABLE AUTOS (
	ID_AUTO CHAR(10) NOT NULL PRIMARY KEY,	/*El id del auto es la serie del motor*/
	PRECIO DOUBLE NOT NULL,
	CILINDRADA CHAR(10) NOT NULL,
	ID_MODELO CHAR(20) NOT NULL,

	CONSTRAINT FOREIGN KEY(ID_MODELO) REFERENCES MODELOS(ID_MODELO)
);

CREATE TABLE VENTAS (
	ID_AUTO CHAR(10) NOT NULL,
	ID_PERSONAL CHAR(10) NOT NULL,
	ID_CLIENTE CHAR(10) NOT NULL,
	MATRICULA CHAR(10) NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	TOTAL_VENTA DOUBLE NOT NULL,

	PRIMARY KEY(ID_AUTO, ID_PERSONAL, ID_CLIENTE),

	CONSTRAINT FOREIGN KEY(ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL),
	CONSTRAINT FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
	CONSTRAINT FOREIGN KEY(ID_AUTO) REFERENCES AUTOS(ID_AUTO)
);